### ISSUE TITLE
Wireguard on Romania server fails to connect

### ISSUE THREAD

**Issue by gurabli** [binhex/arch-qbittorrentvpn#66] opened 2020-11-24 11:21 UTC
All the servers I have tried fire up and run great using Wireguard, except Romania.

Editing wg0.conf to:

`Endpoint = ro.privacy.network:1337`

results in:
```
2020-11-24 11:18:31,621 DEBG 'start-script' stderr output:
parse error: Invalid numeric literal at line 4, column 0
2020-11-24 11:18:31,696 DEBG 'start-script' stdout output:
[warn] Unable to successfully download PIA json to generate token from URL 'https://89.38.224.170
143.244.52.1/authv3/generateToken'
[info] Retrying in 10 secs...
```
Not sure if this is PIA related or the container. 
Using PIA app (desktop or Android) it connects fine to Romania server using Wireguard.

**Comment by binhex** [comment] 2020-11-25 09:20
if its failing on one endpoint only then the finger of blame points firmly at PIA, i would raise a ticket with PIA and tell them that its not possible to get a working port forward for Romania when using an OpenVPN client and the 'Manual PIA VPN Connections', as linked here:- https://github.com/pia-foss/manual-connections

**Comment by gurabli** [comment] 2020-12-02 10:59
> if its failing on one endpoint only then the finger of blame points firmly at PIA, i would raise a ticket with PIA and tell them that its not possible to get a working port forward for Romania when using an OpenVPN client and the 'Manual PIA VPN Connections', as linked here:- https://github.com/pia-foss/manual-connections

So I get this reply from pia-foss:

> I see that your error is:
> 
> [warn] Unable to successfully download PIA json to generate token from URL 'https://89.38.224.170
> 143.244.52.1/authv3/generateToken'
> This looks like a string concatenation error. It looks like you have ip1 + "\n" + ip2. Please ask your developer to have a look at the code.
> 
> That warning message is not a message from this repository, so I have to close this ticket.

No a little confused.

**Comment by binhex** [comment] 2020-12-02 15:53
ok so the warning reported is indeed showing two IP addresses, this is populated by querying the PIA API and getting the IP address for the endpoint, which in this case is Romania. So the issue is still a PIA related one, but i MIGHT be able to work around this by just getting the first IP address, not that that guarantees it's the correct one if multiples are shown, but its all i can do.

**Comment by binhex** [comment] 2020-12-02 16:15
ive figured it out!, it was caused by a partial match, so ```ro.privacy.network``` also matches ```monteneg**ro.privacy.network**``` and thus it reports two ip addresses!!. i have now switched it to an anchored regex to prevent this, fix is in and i will kick off a build shortly which should fix this up for you, i will let you know when its ready to be tested.

**Comment by gurabli** [comment] 2020-12-02 16:16
I don't know much about the internal structure how it works.
Maybe you consult directly with PIA-foss?
It does work for all the other European servers I use, except this one, so there must be an error or missconfiguration somewhere (be it PIA side or not).
Thanks for looking into this.

**Comment by gurabli** [comment] 2020-12-02 16:18
> ive figured it out!, it was caused by a partial match, so `ro.privacy.network` also matches `montenegro.privacy.network` and thus it reports two ip addresses!!. i have now switched it to an anchored regex to prevent this, fix is in and i will kick off a build shortly which should fix this up for you, i will let you know when its ready to be tested.

Posting at same time :) 
Excellent, many thanks. Will watch and test when you say it is ready to be pulled.

**Comment by binhex** [comment] 2020-12-02 16:45
OK there is now a 'test' tagged image, please pull this down and see if the issue is resolved, let me know so i can push this out to latest.

**Comment by gurabli** [comment] 2020-12-02 17:24
> OK there is now a 'test' tagged image, please pull this down and see if the issue is resolved, let me know so i can push this out to latest.

Pulled the test image, Romanian server fired up, it works fine. 
I grabbed two Ubuntu builds, looks everything fine. 
Much appreciated for fixing this.

**Closed** 2020-12-02 17:30 UTC
